spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: petclinic
  datasource:
##    schema: classpath*:db/mysql/schema.sql
##    data: classpath*:db/mysql/data.sql
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
#     url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
##    url: jdbc:mysql://172.16.24.195:3306/petclinic?useSSL=false
#     url: jdbc:mysql://47.99.138.113:3306/petclinic?useSSL=false
##    username: root
##    password: justpwd
##    initialization-mode: NEVER
##    sleuth:
##      sampler:
##        percentage: 1.0

server.port: 0
# JPA
spring.jpa.hibernate.ddl-auto: none
# spring.jpa.hibernate.ddl-auto: update
# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false
# Enable all Actuators and not only the two available by default /health and /info starting Spring Boot 2.0
management.endpoints.web.exposure.include: "*"
# Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
# Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
spring.cloud.refresh.refreshable: false
# Logging
logging.level.org.springframework: INFO
# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

