spring:
  profiles:
    active:
    - dev
---
# server:
#   port: 8001
server: 
  compression:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: justpwd
    key-store-type: PKCS12
    protocol: TLSv1.2
    key-alias: undertow
  http2:
    enabled: true
spring:
  profiles: dev
  application: 
    name: customers-service
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
#     instance-id: customers-service_1
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: https://localhost:8761/eureka
#       defaultZone: http://172.16.24.195:8761/eureka/
#       defaultZone: http://47.99.138.113:8761/eureka/
