spring:
  profiles:
    active:
    - dev
---
# server:
#   port: 8001
spring:
  profiles: dev
  application: 
    name: customers-service
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
#     instance-id: customers-service_1
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/
#       defaultZone: http://172.16.24.195:8761/eureka/
#       defaultZone: http://47.99.138.113:8761/eureka/
