spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: discovery
server:
  port: 8761
  compression:
    enabled: true
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: justpwd
    key-store-type: PKCS12
    protocol: TLSv1.2
    key-alias: undertow
  http2:
    enabled: true
eureka:
  instance:
    hostname: localhost
#    hostname: 172.16.24.195
#     hostname: 47.99.138.113
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/

